CREATE database customer;
USE customer;
SELECT * FROM customer_data;
DESCRIBE customer_data;

-- Q1. Total revenue generated by male vs. female customer?
SELECT gender, SUM(purchase_amount) as revenue
FROM customer_data
GROUP BY gender;

-- Q2. Customer used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount, (SELECT AVG(purchase_amount) FROM customer_data) AS avg_purchase_amount FROM customer_data
WHERE discount_applied = 'Yes' and purchase_amount >= (SELECT AVG(purchase_amount) FROM customer_data);

-- Top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating),2) AS avg_rating
FROM customer_data
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;

-- Compare the average purchase amounts between standard and express shipping.
SELECT shipping_type, ROUND(AVG(purchase_amount), 2) 
FROM customer_data
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;


-- Do subscribed customers spend more ? compare average spend and total revenue between subscribers and non-subscribers
SELECT subscription_status, 
COUNT(customer_id) AS total_customer, 
ROUND(AVG(purchase_amount),2) AS avg_spend,
ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer_data
GROUP BY subscription_status;

-- which 5 products have the highest percentage of purchases with discounts applied?
SELECT 
    item_purchased,
    ROUND(
        (SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0) / COUNT(*),
        2
    ) AS discount_percentage
FROM customer_data
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

-- segment customer into new, returning, and loyal based on their total number of previous purchases, and show the count of each segment
SELECT 
	CASE
		WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 1 AND 10 THEN 'Returning'
        ELSE 'Loyal'
	END AS customer_segment,
    COUNT(*) AS customer_count
FROM customer_data
GROUP BY customer_segment;


-- The top 3 most purchased products within each category
WITH product_count AS (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS total_purchases
    FROM customer_data
    GROUP BY category, item_purchased
),

ranked_products AS (
    SELECT 
        category,
        item_purchased,
        total_purchases,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY total_purchases DESC
        ) AS rank_num
    FROM product_count
)

SELECT 
	rank_num,
    category,
    item_purchased,
    total_purchases
FROM ranked_products
WHERE rank_num <= 3
ORDER BY category, total_purchases DESC;

-- Are customers who are repeat buyers (more than 5 purchases) also likely to subscribe?
SELECT subscription_status, COUNT(customer_id) AS repeat_buyers
FROM customer_data
WHERE previous_purchases > 5
group by subscription_status;

-- Revenue contribution of each age group
SELECT age_group,
SUM(purchase_amount) AS total_revenue
FROM customer_data
GROUP BY age_group
ORDER BY total_revenue DESC;




